name: teste_unidade
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  bloc: ^7.0.0
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.0
  mocktail: ^0.0.1-dev.11
